#!/usr/bin/env node
const cmd = require('.')

cmd
  .version('0.0.1')
  .option('-n, --name', 'show the name', () => console.log('His name is ZYSzys.'))
  .option('-a, --age-now', 'show the age', () => console.log('His age is 20.'))

cmd
  .command('init [hello]')
  .description('init repo')
  .action(function (hello) {
    console.log(`init ${hello} okkkkkk ! !`)
  })
console.log(process.argv)
cmd.parse(process.argv)


